context:
  version: 0.8.0

package:
  name: husky.net
  version: ${{ version }}

source:
  - git: https://github.com/alirezanet/husky.net
    tag: v${{ version }}
  - url: https://github.com/alirezanet/Husky.Net/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ec1933e0fb73cf0517fd007d325603007aa65ce430267a70fc78cfea43d9716e
    target_directory: archive

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - git
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-husky --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git hooks made easy with Husky.Net internal task runner!
  homepage: https://github.com/alirezanet/husky.net
  repository: https://github.com/alirezanet/husky.net

extra:
  recipe-maintainers:
    - danielnachun
