context:
  version: "0.9.1"

package:
  name: husky.net
  version: ${{ version }}

source:
  - git: https://github.com/alirezanet/husky.net
    tag: v${{ version }}
  - url: https://github.com/alirezanet/Husky.Net/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 65830c55b2942bb8221ff46fa7cc141fe36531b7530cb1bdd12a3f8cf5c9d970
    target_directory: archive

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - git
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-husky --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git hooks made easy with Husky.Net internal task runner!
  homepage: https://github.com/alirezanet/husky.net
  repository: https://github.com/alirezanet/husky.net

extra:
  recipe-maintainers:
    - danielnachun
